### PR TITLE
Fix #137

### LINKED ISSUE #137: Symfony\Component\Debug\Exception\FatalThrowableError in App\Notifications\GeneralInterestNotification
## Error in Apiary

**Symfony\Component\Debug\Exception\FatalThrowableError** in **App\Notifications\GeneralInterestNotification**
Call to a member function routeNotificationFor() on string

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/59aab748c1d5f4001828f5f2?event_id=59aab748c1d5f4001828f5f1&i=gh&m=ci)

## Stacktrace

    vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php:48 - Illuminate\Notifications\Channels\MailChannel::send

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/59aab748c1d5f4001828f5f2?event_id=59aab748c1d5f4001828f5f1&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

### PR DESCRIPTION
**Pull request by RossIV**
Turns out my original change for #137 isn't quite what was needed. But this should work.

### CODE REVIEW

File: app/Http/Controllers/NotificationController.php [hunk 1]
```diff
@@ -6,6 +6,7 @@
 use App\Notifications\GeneralInterestNotification;
 use Carbon\Carbon;
 use Notification;
+use Mail;
```
Comment (kberzinch) [inline app/Http/Controllers/NotificationController.php]: You're no longer using `Mail`.

**Comment by RossIV** [comment]
Changed.
