### PR TITLE
General RAL fixes

### LINKED ISSUE #2528: Nova not accepting valid Google Meet links for redirects

### LINKED ISSUE #2543: Add support for GT Zoom URLs for remote attendance links

### PR DESCRIPTION
**Pull request by JoshOldenburg**
Do not require URL validation for RAL creation as it requries a scheme. The regex will ensure it is valid. Fixes #2528.

Add support for Zoom links to RALs. Fixes #2543.

### CODE REVIEW

**Review by kberzinch — CHANGES_REQUESTED** [review]
Unit tests are failing. Not sure why the build still passed...

File: app/Nova/RemoteAttendanceLink.php [hunk 1]
```diff
@@ -145,7 +145,7 @@ public function fields(Request $request): array
                 ->rules('nullable', 'url')
                 ->help('If you put a link here, everyone who clicks the attendance link will be redirected to that '.
                     'meeting after their attendance is recorded. If you add a redirect URL, do not share that URL '.
-                    'directly. Only Google Meet, BlueJeans, and Microsoft Teams calls are supported currently in the '.
```
Comment (kberzinch) [inline app/Nova/RemoteAttendanceLink.php:148]: Add zoom

**Review by kberzinch — CHANGES_REQUESTED** [review]

**Review by kberzinch — APPROVED** [review]
