### PR TITLE
Tweak dues packages in Nova

### LINKED ISSUE #1848: Add help text in Nova on Dues Package date fields

### LINKED ISSUE #1863: Illuminate\Database\QueryException in GET /nova-api/dues-packages
## Error in Apiary

**Illuminate\Database\QueryException** in **GET /nova-api/dues-packages**
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_active' in 'order clause' (SQL: select * from `dues_packages` where `dues_packages`.`deleted_at` is null order by `is_active` asc limit 26 offset 0)

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/60fb1ad11089c50007635b06?event_id=60fb1ad1007fa4ab23980000&i=gh&m=ci)

## Stacktrace

    app/Http/Middleware/CASAuthenticate.php:100 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/60fb1ad11089c50007635b06?event_id=60fb1ad1007fa4ab23980000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

### PR DESCRIPTION
**Pull request by kberzinch**
- Make active field not sortable (fixes #1863)
- Add help text to date fields (fixes #1848)

### CODE REVIEW

File: app/Nova/DuesPackage.php [hunk 1]
```diff
@@ -156,10 +164,18 @@ public function fields(Request $request): array
                     ->onlyOnDetail(),
 
                 DateTime::make('Access Start Date', 'access_start')
+                    ->help(
```
Comment (evan10s) [inline app/Nova/DuesPackage.php:167]: I would add that it's normal for this date range to be different/longer than the effective date range.

Comment (kberzinch) [reply app/Nova/DuesPackage.php:167]: Good call.

Comment (kberzinch) [reply app/Nova/DuesPackage.php:167]: Added a sentence

**Review by evan10s — APPROVED** [review]
