### PR TITLE
Rebuild Square integration

### LINKED ISSUE #240: Enter transaction fees as a "tax"
Calculate the appropriate percentage amount to add a $3 surcharge to the transaction, then add it as a tax with label "Card Processing Fee".

This is slightly dumb, yes.

### LINKED ISSUE #448: Log error in GET /payments/complete
## Error in Apiary

**Log error** in **GET /payments/complete**
App\Http\Controllers\PaymentController - Error querying Square transaction

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5b95923f8ed4870019c5951c?event_id=5b9eb6d7002ec81d85010000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/PaymentController.php:496 - App\Http\Controllers\PaymentController::getSquareTransaction
    app/Http/Controllers/PaymentController.php:413 - App\Http\Controllers\PaymentController::handleSquareResponse
    app/Http/Middleware/CASAuthenticate.php:63 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5b95923f8ed4870019c5951c?event_id=5b9eb6d7002ec81d85010000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

### LINKED ISSUE #449: Symfony\Component\Debug\Exception\FatalThrowableError in GET /payments/complete
## Error in Apiary

**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /payments/complete**
Call to undefined method SquareConnect\ApiException::getTransaction()

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5b95923f8ed4870019c5951b?event_id=5b9eb6d7002ec81d85010001&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/PaymentController.php:433 - App\Http\Controllers\PaymentController::handleSquareResponse
    app/Http/Middleware/CASAuthenticate.php:63 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5b95923f8ed4870019c5951b?event_id=5b9eb6d7002ec81d85010001&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

### LINKED ISSUE #480: Transaction fees are not being correctly received from prod square

### LINKED ISSUE #517: Rebuild Square Checkout processing

### LINKED ISSUE #518: Consider using Square webhooks for transaction alerting
This may get us transaction fees and catch any payments run during maintenance maybe? To discuss.

### LINKED ISSUE #795: Remove call to deprecated getTransaction method in PaymentController

### LINKED ISSUE #1164: Make credit card fee match what Square charges us

### PR DESCRIPTION
**Pull request by kberzinch**
Summary of changes:
- Factor out Square-related endpoints to a separate controller
- Remove some routes that are no longer necessary
- Update to latest Square SDK
- Add webhook to receive payment events directly from Square

Closes #240 
Closes #448 
Closes #449 
Closes #480 
Closes #517 
Closes #518 
Closes #795
Closes #1164

### CODE REVIEW

File: app/Http/Controllers/SquareController.php [hunk 1]
```diff
@@ -0,0 +1,206 @@
...
+                $q->whereDate('effective_end', '>=', date('Y-m-d'));
+            })->whereHas('payment', static function (Builder $q): void {
+                $q->where('amount', 0.00);
+                $q->where('method', 'square');
+            })->first();
+
+        if (null !== $transactionWithIncompletePayment) {
+            $transaction = $transactionWithIncompletePayment;
+
+            $payment = $transaction->payment[0];
```
Comment (kberzinch) [inline app/Http/Controllers/SquareController.php:50]: The previous implementation reset the `unique_id` here, which would allow for creating duplicate orders. This implementation may result in the `createCheckout` call failing if there is a long period between the first and second times someone attempts payment, but I think that should be ok. We can delete the payment if we need to.

File: app/Http/Controllers/SquareController.php [hunk 2]
```diff
@@ -0,0 +1,206 @@
...
+        $surcharge->setCurrency('USD');
+
+        $orderLineItem = new OrderLineItem('1');
+        $orderLineItem->setName('Dues - '.$transaction->package->name);
+        $orderLineItem->setBasePriceMoney($basePrice);
+
+        $orderServiceCharge = new OrderServiceCharge();
+        $orderServiceCharge->setName('Card Processing Surcharge');
+        $orderServiceCharge->setAmountMoney($surcharge);
+        $orderServiceCharge->setCalculationPhase(OrderServiceChargeCalculationPhase::TOTAL_PHASE);
```
Comment (kberzinch) [inline app/Http/Controllers/SquareController.php:88]: As noted in Slack, this is not exposed in the checkout UX super well. We could switch it to a tax but I think this is more semantically correct and is easier to calculate accurately.

File: app/Http/Controllers/SquareController.php [hunk 3]
```diff
@@ -0,0 +1,206 @@
...
+                    'message' => 'We could not contact Square to begin your payment.',
+                ]
+            );
+        }
+
+        $checkout = $checkoutResponse->getResult()->getCheckout();
+
+        $payment->checkout_id = $checkout->getId();
+        $payment->order_id = $checkout->getOrder()->getId();
+        $payment->save();
```
Comment (kberzinch) [inline app/Http/Controllers/SquareController.php:128]: The `checkout_id` is used to verify the redirect and the `order_id` is used to match up webhook calls. The rest of the IDs in the database aren't necessary anymore (at least for web payments, card-present may still need them?)

File: app/Http/Controllers/SquareController.php [hunk 4]
```diff
@@ -0,0 +1,206 @@
...
+                return redirect('/');
+            case OrderState::CANCELED:
+                return view(
+                    'square.error',
+                    [
+                        'message' => 'Your order was canceled.',
+                    ]
+                );
+            case OrderState::OPEN:
+                return view('square.processing');
```
Comment (kberzinch) [inline app/Http/Controllers/SquareController.php:189]: In this state, the payment would be reconciled via webhooks. It is possible for a user to fake the redirect back to Apiary, but that wouldn't do anything since this case does not actually make any state changes.

File: app/Http/Controllers/SquareController.php [hunk 5]
```diff
@@ -0,0 +1,206 @@
...
+            case OrderState::COMPLETED:
+                $tender = $order->getTenders()[0];
+                $payment->amount = $tender->getAmountMoney()->getAmount() / 100;
+                if (null !== $tender->getProcessingFeeMoney()) {
+                    $payment->processing_fee = $tender->getProcessingFeeMoney()->getAmount() / 100;
+                }
+                $payment->notes = 'Checkout flow completed';
+                $payment->save();
+
+                alert()->success("We've received your payment", 'Success!');
```
Comment (kberzinch) [inline app/Http/Controllers/SquareController.php:178]: This doesn't show the icon for some reason. See also #729

File: app/Http/Controllers/SquareController.php [hunk 6]
```diff
@@ -0,0 +1,206 @@
...
+
+        $order = $retrieveOrderResponse->getResult()->getOrder();
+
+        switch ($order->getState()) {
+            case OrderState::COMPLETED:
+                $tender = $order->getTenders()[0];
+                $payment->amount = $tender->getAmountMoney()->getAmount() / 100;
+                if (null !== $tender->getProcessingFeeMoney()) {
+                    $payment->processing_fee = $tender->getProcessingFeeMoney()->getAmount() / 100;
+                }
```
Comment (kberzinch) [inline app/Http/Controllers/SquareController.php:174]: It seems like the processing fee is not available at this point, but I figured it was worth checking.

File: app/Http/Controllers/SquareController.php [hunk 7]
```diff
@@ -0,0 +1,206 @@
...
+    {
+        return bin2hex(openssl_random_pseudo_bytes(32));
+    }
+
+    private static function calculateSurcharge(int $amount): int
+    {
+        return (int) round(
+            (($amount + self::PER_TRANSACTION_FEE) / ((100 - self::PERCENTAGE_FEE) / 100)) - $amount,
+            0,
+            PHP_ROUND_HALF_UP
```
Comment (kberzinch) [inline app/Http/Controllers/SquareController.php:203]: This is the specific rounding mode Square uses - https://squareup.com/help/us/en/article/5092-rounding

File: app/Jobs/ProcessSquareWebhook.php [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+     */
+    public function handle(): void
+    {
+        $details = $this->webhookCall->payload['data']['object']['payment'];
+
+        $payment = Payment::where('order_id', $details['order_id'])->firstOrFail();
+        $payment->amount = $details['amount_money']['amount'] / 100;
+        if (array_key_exists('processing_fee', $details)) {
+            $payment->processing_fee = $details['processing_fee'][0]['amount_money']['amount'] / 100;
+        }
```
Comment (kberzinch) [inline app/Jobs/ProcessSquareWebhook.php:39]: This webhook is subscribed to both `create` and `update` events, the processing fee is only available in the `update` event.

File: app/Jobs/ProcessSquareWebhook.php [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+        $payment->notes = 'Checkout flow completed';
+        $payment->save();
+
+        $payment->payable->user->notify(new ConfirmationNotification($payment));
```
Comment (kberzinch) [inline app/Jobs/ProcessSquareWebhook.php:43]: This will fire twice. Not sure what to do about it. Only fire on `create` events?

File: resources/js/components/PaymentInstructions.vue [hunk 10]
```diff
@@ -11,10 +11,8 @@
               Credit/Debit Card
             </h4>
             <p class="card-text">
-              Pay with your credit/debit card online. There is a $3 surcharge to cover payment processing fees.
-                <!-- TODO this needs to be toggleable with the feature flag -->
-                Prefer to pay in-person? See an officer at the shop.<br/>
```
Comment (kberzinch) [inline resources/js/components/PaymentInstructions.vue:16]: Even post-COVID I don't think it's a good use of time to advertise this. Open to other opinions.

File: app/Http/Controllers/SquareController.php (hunk 1 above)
Comment (kberzinch) [reply app/Http/Controllers/SquareController.php:50]: We could add a listener for order events and then clean up (how?) payments that would no longer work.

File: app/Jobs/ProcessSquareWebhook.php (hunk 9 above)
Comment (JoshOldenburg) [reply app/Jobs/ProcessSquareWebhook.php:43]: Only firing on `create` sounds fine.

**Review by JoshOldenburg — CHANGES_REQUESTED** [review]
Looking good. I believe the duplicate notifications is the only blocking issue right now.

File: app/Http/Controllers/SquareController.php (hunk 2 above)
Comment (kberzinch) [reply app/Http/Controllers/SquareController.php:88]: I did, no difference.

Comment (JoshOldenburg) [reply app/Http/Controllers/SquareController.php]: Okay, that's fine then.

**Review by JoshOldenburg — DISMISSED** [review]

File: app/Http/Controllers/SquareCheckoutController.php [hunk 11]
```diff
@@ -0,0 +1,221 @@
...
+        $user = $request->user();
+
+        $transactionWithNoPayment = DuesTransaction::doesntHave('payment')
+            ->where('user_id', $user->id)
+            ->latest('updated_at')
+            ->first();
+
+        $transactionWithIncompletePayment = DuesTransaction::where('user_id', $user->id)
+            ->whereHas('package', static function (Builder $q): void {
+                $q->whereDate('effective_end', '>=', date('Y-m-d'));
```
Comment (RossIV) [inline app/Http/Controllers/SquareCheckoutController.php:41]: Do we have an active() local scope that could be used here instead?

File: app/Http/Controllers/SquareCheckoutController.php [hunk 12]
```diff
@@ -0,0 +1,221 @@
...
+                }
+
+                $cardDetails = $tender->getCardDetails();
+                if (null !== $cardDetails) {
+                    $card = $cardDetails->getCard();
+                    if (null !== $card) {
+                        $payment->card_brand = $card->getCardBrand();
+                        $payment->card_type = $card->getCardType();
+                        $payment->last_4 = $card->getLast4();
+                        $payment->prepaid_type = $card->getPrepaidType();
```
Comment (RossIV) [inline app/Http/Controllers/SquareCheckoutController.php:186]: What is this?

File: database/migrations/2020_12_22_105909_create_webhook_calls_table.php [hunk 13]
```diff
@@ -0,0 +1,27 @@
...
+declare(strict_types=1);
+
+use Illuminate\Database\Migrations\Migration;
+use Illuminate\Database\Schema\Blueprint;
+
+class CreateWebhookCallsTable extends Migration
+{
+    public function up(): void
+    {
+        Schema::create('webhook_calls', static function (Blueprint $table): void {
```
Comment (RossIV) [inline database/migrations/2020_12_22_105909_create_webhook_calls_table.php:12]: Is there anything particularly sensitive that will be stored in this table?

**Review by RossIV — COMMENTED** [review]
Questions...

File: app/Http/Controllers/SquareCheckoutController.php (hunk 12 above)
Comment (kberzinch) [reply app/Http/Controllers/SquareCheckoutController.php:186]: Flag from Square that indicates whether this is a prepaid card or not.

File: database/migrations/2020_12_22_105909_create_webhook_calls_table.php (hunk 13 above)
Comment (kberzinch) [reply database/migrations/2020_12_22_105909_create_webhook_calls_table.php:12]: It will store [`payment.created`](https://developer.squareup.com/reference/square/payments-api/webhooks/payment.created) and [`payment.updated`](https://developer.squareup.com/reference/square/payments-api/webhooks/payment.updated) events. There are lots of fields there that are not super fun to store, but given that nothing in the table will be exposed via Nova or API I think we should be OK?

File: app/Http/Controllers/SquareCheckoutController.php (hunk 11 above)
Comment (kberzinch) [reply app/Http/Controllers/SquareCheckoutController.php:41]: Yes. Would that just be...

```diff
 $transactionWithIncompletePayment = DuesTransaction::where('user_id', $user->id)
-    ->whereHas('package', static function (Builder $q): void {
-        $q->whereDate('effective_end', '>=', date('Y-m-d'));
-    })->whereHas('payment', static function (Builder $q): void {
+    ->current()
+    ->whereHas('payment', static function (Builder $q): void {
         $q->where('amount', 0.00);
         $q->where('method', 'square');
     })->first();
```

Comment (RossIV) [reply app/Http/Controllers/SquareCheckoutController.php:41]: Yes, that looks correct. Note that the DuesPackage active() scope checks both effective start and end.

**Review by RossIV — APPROVED** [review]
