### PR TITLE
FiscalYear metrics

### LINKED ISSUE #598: Nova metric for total dues paying members since August
I.e. total unique members in the current academic year

### LINKED ISSUE #830: PaymentsPerDay Nova card is invalid
It should use `updated_at`, not `created_at`, because `Payment`s are updated when the Square payment actually goes through. Additionally, it should ignore payments with a zero amount.

### LINKED ISSUE #1515: Payment methods card on dues packages is broken

### PR DESCRIPTION
**Pull request by kberzinch**
Summary of changes:
- Reorder metrics on `DuesPackage`s so that related cards are visually nearer to each other
- Copy `DuesPackage` metrics to `FiscalYear`s and update calculations to support that
- Add `DuesRevenueByFiscalYear` and `MembersByFiscalYear` trends to the main dashboard
- Fixes #1515
- Fixes #830 
- Closes #598

### CODE REVIEW

**Review by RossIV — APPROVED** [review]

File: app/Nova/DuesPackage.php [hunk 1]
```diff
@@ -80,6 +87,16 @@ public function fields(Request $request): array
             BelongsTo::make('Fiscal Year', 'fiscalYear', FiscalYear::class)
                 ->sortable(),
 
+            Number::make('Transactions', function (): int {
```
Comment (JoshOldenburg) [inline app/Nova/DuesPackage.php:90]:
```suggestion
            Number::make('Paid Transactions', function (): int {
```

**Review by JoshOldenburg — CHANGES_REQUESTED** [review]
Looks good, one minor wording suggestion

**Review by JoshOldenburg — APPROVED** [review]
