### PR TITLE
Dues Flow Fixes

### LINKED ISSUE #1577: Dues dropdown is wonky for Chrome on Mac

### LINKED ISSUE #1650: Handle 422s gracefully in dues flow
This is fixed-ish on the profile page but not in the dues flow, or at least not everywhere.

### LINKED ISSUE #1914: When updating user during dues flow, only send the changed fields to the server
For example, in `DuesRequiredInfo.vue` during the `submit` method

### PR DESCRIPTION
**Pull request by RossIV**
Mostly frontend...
Closes #1650 (Handle 422s in dues flow)
Closes #1914 (Send only changed fields in dues flow)
Closes #1577 (Fix glitchy dues dropdown on Chrome on Mac)

### CODE REVIEW

File: app/Jobs/RetrieveIpAddressGeoLocationForSignature.php [hunk 1]
```diff
@@ -58,17 +60,22 @@ public function handle(): void
...
+                        'output' => 'json',
+                    ],
+                ]
+            );
 
-        $this->signature->ip_address_location_estimate = json_decode($response->getBody()->getContents());
-        $this->signature->save();
+            $this->signature->ip_address_location_estimate = json_decode($response->getBody()->getContents());
+            $this->signature->save();
+        } catch (ClientException $e) {
```
Comment (kberzinch) [inline app/Jobs/RetrieveIpAddressGeoLocationForSignature.php:76]: I would rather just bubble up the exception, you get more info in horizon that way

**Review by kberzinch — CHANGES_REQUESTED** [review]

File: app/Jobs/RetrieveIpAddressGeoLocationForSignature.php (hunk 1 above)
Comment (RossIV) [reply app/Jobs/RetrieveIpAddressGeoLocationForSignature.php:76]: That doesn't help local dev though, because when the queue driver is `sync` the exception gets rendered to the user and then you have to restart the dues flow.

Comment (RossIV) [reply app/Jobs/RetrieveIpAddressGeoLocationForSignature.php:76]: Compromise - leave the handler, and I'll still pass the exception up via the failure handler.

File: resources/js/components/dues/DuesRequiredInfo.vue [hunk 2]
```diff
@@ -190,6 +190,26 @@ export default {
...
+            error.response.status === 422 &&
+            error.response.data &&
+            error.response.data.errors &&
+            typeof error.response.data.errors === 'object' && Object.keys(error.response.data.errors).length > 0 &&
+            typeof error.response.data.errors[Object.keys(error.response.data.errors)[0]] === 'object' &&
+            error.response.data.errors[Object.keys(error.response.data.errors)[0]].length > 0
+          ) {
+            const message = error.response.data.message;
+            const errors = error.response.data.errors;
+            let validation_messages = []
```
Comment (evan10s) [inline resources/js/components/dues/DuesRequiredInfo.vue:205]: I think this can be a `const` even if you add entries to the array (just JS things).  `let` allows the entire variable to be reassigned to a completely different value

File: resources/js/components/dues/DuesRequiredInfo.vue [hunk 3]
```diff
@@ -190,6 +190,26 @@ export default {
...
+            Object.entries(errors).forEach(([prop, val]) => validation_messages.push(val));
+            Swal.fire({
+                title: 'Validation Error',
+                html: '<b>' + message + '</b><br/>' + validation_messages.join('<br/>'),
```
Comment (evan10s) [inline resources/js/components/dues/DuesRequiredInfo.vue:209]: Use string interpolation

**Review by evan10s — CHANGES_REQUESTED** [review]
lgtm but a few JS style issues

**Review by kberzinch — APPROVED** [review]

File: resources/js/components/dues/DuesRequiredInfo.vue [hunk 4]
```diff
@@ -190,6 +190,26 @@ export default {
...
             this.$emit('next');
+          } else if (
+            error &&
+            error.response &&
+            error.response.status === 422 &&
+            error.response.data &&
+            error.response.data.errors &&
+            typeof error.response.data.errors === 'object' && Object.keys(error.response.data.errors).length > 0 &&
+            typeof error.response.data.errors[Object.keys(error.response.data.errors)[0]] === 'object' &&
+            error.response.data.errors[Object.keys(error.response.data.errors)[0]].length > 0
```
[the remark this answers is not in the document]
Comment (RossIV) [reply resources/js/components/dues/DuesRequiredInfo.vue:201]: I'm pulling the lazy card and am gonna say someone else can do this

**Review by evan10s — APPROVED** [review]

**Review by JoshOldenburg — APPROVED** [review]
